Создание компонента Calendar
js-tasks-ru/htmlcss-20220414_pmalian pull request #10
Opened 2022-04-29 15:25 UTC by yuKalashnikova2

добалены шрифт в fonts.css и добавлен новый цвет --blue-2 в переменную

2022-04-29 15:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-29 18:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-30 10:57 UTC, GSemikozov requested changes

2022-04-30 10:57 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-left: 24px;
padding: 28px 26px

2022-04-30 10:57 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__title__one {
.histogram__title

2022-04-30 10:57 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__title__two {
.histogram__link

2022-04-30 10:57 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__numbers {
а вообще мне кажется мы ревьюили этот блок в другом ПР - надо подлить сюда свежим апстрим мастер если решение по задаче принято

2022-04-30 10:57 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 36px;
28 26

2022-04-30 10:57 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item__day {
.calendar__item_day

2022-04-30 10:57 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item__day {
и еще не хватает модификаторов для выборки дней (range)

2022-04-30 10:57 UTC, GSemikozov commented on components/page/page.css
> +.page__main__title {
.page__title

2022-04-30 10:57 UTC, GSemikozov commented on components/page/page.css
> +.page__aside__title {
.page__aside-title

2022-04-30 10:57 UTC, GSemikozov commented on components/page/page.css
> +.page__footer__title {
.page__footer-title

2022-04-30 10:57 UTC, GSemikozov commented on components/page/page.css
> +li {
элементы списка в контексте БЭМ блока реализованы через селекторы тегов - это ошибка

2022-05-03 13:01 UTC, yuKalashnikova2 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__numbers {
все верно, это по гистограмме, видимо опять изменения гистограммы не туда положила, это ветка календарь

2022-05-05 09:34 UTC, closed without merging