создание tooltip
js-tasks-ru/htmlcss-20220414_pmalian pull request #11
Opened 2022-04-29 19:27 UTC by yuKalashnikova2

2022-04-29 19:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-29 19:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-30 10:51 UTC, GSemikozov requested changes

2022-04-30 10:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    width: 100px;
зачем же так жестко фиксировать?) в качестве триггера для вызова подсказки может использоваться как иконка 24х24, так и вообще любой другой элемент, так что фиксировать размеры как 100х100 очень не практично

2022-04-30 10:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: 0 auto;
это должен быть inline-block, + никаких марджинов на уровне блока

2022-04-30 10:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    padding-top: 62px;
это лишнее, удалим

2022-04-30 10:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    background: #4263EB;
цвета проставялем из css-переменных

2022-04-30 10:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top:65%;
bottom: calc(100% + высота стрелки)

2022-04-30 10:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: 100%;
top: 100%

2022-04-30 10:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    left: 40%;
left: calc(50% - половина ширины стрелки)

2022-05-03 13:33 UTC, yuKalashnikova2 commented
внесла изменения

2022-05-04 10:04 UTC, GSemikozov requested changes

2022-05-04 10:04 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top:65%;
а top тогда удалить

2022-05-04 10:04 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: 100%;
не исправлено

2022-05-04 10:04 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    left: calc(50% - 14px);
а почему -14? ширина стрелки 28? сместить влево надо на половину ширины стрелки)

2022-05-04 10:18 UTC, GSemikozov requested changes

2022-05-04 10:18 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: calc(100% + 62px)
почему 62? 62. -это высота всплывающего элемента, а не стрелки)

2022-05-04 19:27 UTC, GSemikozov requested changes

2022-05-04 19:27 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: 20px;
top + left - удалить, в БЭМ внешнее позиционирование на уровне блока запрещено (чтобы понять почему - достаточно попробовать добавить такой тултип в любой текстовый элемент и посмотреть что будет)

2022-05-04 19:27 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: calc(100% + 62px)
до сих пор не понимаю почему здесь и на 1 строку выше 62? должна же быть какая-то логика)
как мне видится, логика должна быть следующей: если мы хотим выравнивать по середине горизонтально - значить сместим всплывашку на 50%, а затем через transform: translateX() по горизонтальной оси сместим назад на половину ширину элемента (129 / 2 = ~ 65). Затем нужно по вертикали расположить всплывашку четко надо иконкой, при этом учесть высоту стрелки, значит - bottom: calc(100% + высота стрелки), при этом высота стрелки не может быть 62px

2022-05-04 19:27 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    left: calc(50% - 14px);
стрелка должна смотреть вниз, значит выше - border-top, а здесь - отнимаем половину ширины стрелки, чтобы она была по середине

2022-05-04 19:27 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    position: absolute;
иконка не должна никаким специальным образом позиционироваться

2022-05-04 19:27 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: -17vh;
удалить

2022-05-04 19:27 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    right: -1vw;
удалить

2022-05-07 13:12 UTC, GSemikozov requested changes

2022-05-07 13:12 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body { padding: 100px; text-align:center; }
на уровне блока / компонента никогда не описываем глобальные стили. В данном случае они нужны только на странице примера реализации, чтобы всплывашка всплывала не за экраном. Но - тогда эти стили можно добавить на саму хтмл страницу, в тег style внутри head

2022-05-07 20:30 UTC, GSemikozov approved these changes

2022-05-07 20:30 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-05-07 20:31 UTC, GSemikozov approved these changes

2022-05-07 20:31 UTC, merged