календарь от master
js-tasks-ru/htmlcss-20220414_pmalian pull request #15
Opened 2022-05-05 10:02 UTC by yuKalashnikova2

добавлено два класса-модификатора, добавлено 2 шрифта в fonts и переменная цвета blue. Календарь переделан от ветки master

2022-05-05 10:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-05 16:56 UTC, GSemikozov requested changes

2022-05-05 16:56 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item__day {
.calendar__item--day

2022-05-07 07:05 UTC, yuKalashnikova2 commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item__day {
исправлено

2022-05-07 07:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-07 07:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-07 07:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-07 13:14 UTC, GSemikozov approved these changes

2022-05-07 13:15 UTC, merged