Buttons component
js-tasks-ru/htmlcss-20220414_pmalian pull request #4
Opened 2022-04-22 20:51 UTC by yuKalashnikova2

2022-04-22 20:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-26 08:08 UTC, GSemikozov requested changes

2022-04-26 08:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
box-sizing: border-box; уже задан в .button_alternate, не нужно везде дублировать)

2022-04-26 08:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin-bottom: 10px;
марджины на уровне блока не задаем

2022-04-26 08:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: white;
`var(--white)`

2022-04-26 08:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину лучше жестко не фиксировать (текста внутри может быть в несколько раз больше), поэтому я бы предложил удалить. Вместо этого - лучше задать внутренние отступы как в дизайне (padding: 15px 14px 14px)

2022-04-26 17:53 UTC, yuKalashnikova2 commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
удалила везде

2022-04-26 17:53 UTC, yuKalashnikova2 commented on 03-lection1/01-button/button.css
> +    margin-bottom: 10px;
ок

2022-04-26 17:53 UTC, yuKalashnikova2 commented on 03-lection1/01-button/button.css
> +    color: white;
переписала

2022-04-26 17:53 UTC, yuKalashnikova2 commented on 03-lection1/01-button/button.css
> +    width: 189px;
убрала ширину и написала паддинг

2022-04-27 08:37 UTC, GSemikozov approved these changes

2022-04-27 08:37 UTC, merged