добавлена директория card,карточки и prewiw_inner
js-tasks-ru/htmlcss-20220414_pmalian pull request #6
Opened 2022-04-27 18:31 UTC by yuKalashnikova2

задание вне задачника: разместить 3 карточки с помощью технологии display-flex

2022-04-27 18:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 19:55 UTC, GSemikozov requested changes

2022-04-27 19:55 UTC, GSemikozov commented on components/card/card.css
> +.prewiew__inner--card {
если делаем пока карточку как элемент превью а не отдельный компонент - тогда эти стили надо унести в блок preview

2022-04-27 19:55 UTC, GSemikozov commented on components/card/card.css
> +    width: 31.333%;
calc(33.3333% - 30px)

2022-04-27 19:55 UTC, GSemikozov commented on components/preview/preview.css
> +    gap:5px;
30px

2022-04-27 19:55 UTC, GSemikozov commented on components/preview/preview.css
> +    justify-content: space-evenly;
space-between (снаружи отступов не должно быть)

2022-04-28 06:42 UTC, yuKalashnikova2 commented on components/card/card.css
> +.prewiew__inner--card {
ок

2022-04-28 06:42 UTC, yuKalashnikova2 commented on components/card/card.css
> +    width: 31.333%;
исправлено

2022-04-28 06:42 UTC, yuKalashnikova2 commented on components/preview/preview.css
> +    gap:5px;
исправлено

2022-04-28 06:42 UTC, yuKalashnikova2 commented on components/preview/preview.css
> +    justify-content: space-evenly;
ок

2022-04-28 06:50 UTC, yuKalashnikova2 reviewed
изменения добавлены

2022-04-30 10:54 UTC, GSemikozov approved these changes

2022-04-30 10:54 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-04-30 10:58 UTC, GSemikozov approved these changes

2022-04-30 10:58 UTC, merged